# Generated by Django 5.0.4 on 2024-04-28 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoardGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                ("creator", models.CharField(max_length=150, verbose_name="Créateur")),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Disponible"),
                ),
            ],
            options={
                "verbose_name": "Jeu de Plateau",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Disponible"),
                ),
                ("author", models.CharField(max_length=150, verbose_name="Auteur")),
            ],
            options={
                "verbose_name": "livre",
            },
        ),
        migrations.CreateModel(
            name="Cd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Disponible"),
                ),
                ("artist", models.CharField(max_length=150, verbose_name="Artiste")),
            ],
            options={
                "verbose_name": "CD",
            },
        ),
        migrations.CreateModel(
            name="Dvd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Disponible"),
                ),
                (
                    "realizator",
                    models.CharField(max_length=150, verbose_name="Réalisateur"),
                ),
            ],
            options={
                "verbose_name": "DVD",
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nom")),
                ("email", models.EmailField(max_length=100, verbose_name="Mail")),
            ],
            options={
                "verbose_name": "Membre",
            },
        ),
        migrations.CreateModel(
            name="EmpruntDvd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_emprunt", models.DateField(auto_now=True)),
                ("date_restitution", models.DateField(null=True)),
                ("lock", models.BooleanField(default=False)),
                (
                    "state",
                    models.CharField(
                        choices=[("encours", "Encours"), ("rendu", "Rendu")],
                        max_length=15,
                    ),
                ),
                (
                    "dvd",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bibliothecaire.dvd",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bibliothecaire.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emprunt DVD",
            },
        ),
        migrations.CreateModel(
            name="EmpruntCd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_emprunt", models.DateField(auto_now=True)),
                ("date_restitution", models.DateField(null=True)),
                ("lock", models.BooleanField(default=False)),
                (
                    "state",
                    models.CharField(
                        choices=[("encours", "Encours"), ("rendu", "Rendu")],
                        max_length=15,
                    ),
                ),
                (
                    "cd",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bibliothecaire.cd",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bibliothecaire.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emprunt CD",
            },
        ),
        migrations.CreateModel(
            name="EmpruntBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_emprunt", models.DateField(auto_now=True)),
                ("date_restitution", models.DateField(null=True)),
                ("lock", models.BooleanField(default=False)),
                (
                    "state",
                    models.CharField(
                        choices=[("encours", "Encours"), ("rendu", "Rendu")],
                        max_length=15,
                    ),
                ),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bibliothecaire.book",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bibliothecaire.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emprunt livre",
            },
        ),
        migrations.CreateModel(
            name="EmpruntBoardGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_emprunt", models.DateField(auto_now=True)),
                ("date_restitution", models.DateField(null=True)),
                ("lock", models.BooleanField(default=False)),
                (
                    "state",
                    models.CharField(
                        choices=[("encours", "Encours"), ("rendu", "Rendu")],
                        max_length=15,
                    ),
                ),
                (
                    "boardGame",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bibliothecaire.boardgame",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bibliothecaire.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emprunt Jeu Plateau",
            },
        ),
    ]
